name: Claude Mention Handler

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
